[options]
addons_path = /mnt/extra-addons,/var/lib/odoo/addons,/var/lib/odoo/addons/19.0
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$fs.5F6IUgtAaw1hrLcXY2w$rP5BnlYIHNAQrWgryN5.iwNwSapiq/VirugjwubmrBlm8g286pl/jX6IM2vlb25hG6vWD3N92f/Iw4Wu1VYtVg
db_host = db_companyA
db_port = 5432
db_user = odoo
db_password = soukaina
db_name = Company_A

